//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.26 at 12:44:41 AM MSK 
//


package ru.moype.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.moype.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.moype.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Spec }
     * 
     */
    public Spec createSpec() {
        return new Spec();
    }

    /**
     * Create an instance of {@link SpecStr }
     * 
     */
    public SpecStr createSpecStr() {
        return new SpecStr();
    }

    /**
     * Create an instance of {@link GetSpecResponse }
     * 
     */
    public GetSpecResponse createGetSpecResponse() {
        return new GetSpecResponse();
    }

    /**
     * Create an instance of {@link GetSpec }
     * 
     */
    public GetSpec createGetSpec() {
        return new GetSpec();
    }

}
