//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.26 at 12:44:41 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.moype.ru/exchange", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.moype.model;
